version: "3"

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:

  mariadb:
    build: ./MariaDB/
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root123
    networks:
      - customnetwork

  collector:
    build: ./Collecteur/
    ports:
      - "65432"
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10
    depends_on:
      - mariadb

  nginx:
    build: ./Nginx/front_dataviz/
    networks:
      - customnetwork

  api:
    build: ./API/
    networks:
      - customnetwork
    depends_on:
      - mariadb

  automats:
    build: ./UniteProd/
    networks:
      customnetwork:
        ipv4_address: 172.20.0.11
    depends_on:
      - collector
