version: "3"

services:
  mariadb:
    build: ./MariaDB/
    volumes:
      - ./MariaDB/init/:/docker-entrypoint-initdb.d/
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: datas
    ports:
      - "3306:3306"

  collector:
    build: ./Collecteur/
    ports:
      - "65432:65432"
    depends_on:
      - mariadb

  api:
    build: ./API/
    ports:
      - "8081:8080"
    depends_on:
      - mariadb

  nginx:
    build: ./Nginx/front_dataviz_js/
    ports:
      - "81:80"
    depends_on:
      - api

  unit1:
    build: ./UniteProd/
    environment:
      - UNITE_NUMBER=1
    depends_on:
      - collector

  unit2:
    build: ./UniteProd/
    environment:
      - UNITE_NUMBER=2
    depends_on:
      - collector

  unit3:
    build: ./UniteProd/
    environment:
      - UNITE_NUMBER=3
    depends_on:
      - collector

  unit4:
    build: ./UniteProd/
    environment:
      - UNITE_NUMBER=4
    depends_on:
      - collector

  unit5:
    build: ./UniteProd/
    environment:
      - UNITE_NUMBER=5
    depends_on:
      - collector