version: "3"

services:
  mariadb:
    build: ./MariaDB/
    volumes:
      - ./MariaDB/init/:/docker-entrypoint-initdb.d/
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: datas
    ports:
      - "3306:3306"

  collector:
    build:
      context: ./Collecteur
      dockerfile: ./Dockerfile
      args:
        NAME: collector
        MAIL: collector@mail.com
    volumes:
      - ./Collecteur/scripts:/scripts
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "65432:65432"
    depends_on:
      - mariadb

  api:
    build: ./API/
    ports:
      - "8081:8080"
    depends_on:
      - mariadb

  nginx:
    build: ./Nginx/front_dataviz_js/
    ports:
      - "81:80"
    depends_on:
      - api

  unit1:
    build:
      context: ./UniteProd
      dockerfile: ./Dockerfile
      args:
        NAME: unit1
        MAIL: unit1@mail.com
    volumes:
      - ./UniteProd/scripts:/scripts
    environment:
      - UNITE_NUMBER=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - collector

  unit2:
    build:
      context: ./UniteProd
      dockerfile: ./Dockerfile
      args:
        NAME: unit2
        MAIL: unit2@mail.com
    volumes:
      - ./UniteProd/scripts:/scripts
    environment:
      - UNITE_NUMBER=2
      - PYTHONUNBUFFERED=1
    depends_on:
      - collector

  unit3:
    build:
      context: ./UniteProd
      dockerfile: ./Dockerfile
      args:
        NAME: unit3
        MAIL: unit3@mail.com
    volumes:
      - ./UniteProd/scripts:/scripts
    environment:
      - UNITE_NUMBER=3
      - PYTHONUNBUFFERED=1
    depends_on:
      - collector

  unit4:
    build:
      context: ./UniteProd
      dockerfile: ./Dockerfile
      args:
        NAME: unit4
        MAIL: unit4@mail.com
    volumes:
      - ./UniteProd/scripts:/scripts
    environment:
      - UNITE_NUMBER=4
      - PYTHONUNBUFFERED=1
    depends_on:
      - collector

  unit5:
    build:
      context: ./UniteProd
      dockerfile: ./Dockerfile
      args:
        NAME: unit5
        MAIL: unit5@mail.com
    volumes:
      - ./UniteProd/scripts:/scripts
    environment:
      - UNITE_NUMBER=5
      - PYTHONUNBUFFERED=1
    depends_on:
      - collector