version: "3"

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:

  mariadb:
    build: ./MariaDB/
    command: --init-file /data/application/init.sql
    volumes:
        - ./MariaDB/init.sql:/data/application/init.sql
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: datas
    ports:
      - "3306:3306"
    networks:
      - customnetwork

  collector:
    build: ./Collecteur/
    ports:
      - "65432"
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10
    depends_on:
      - mariadb

  nginx:
    build: ./Nginx/front_dataviz/
    networks:
      - customnetwork

  api:
    build: ./API/
    networks:
      - customnetwork
    depends_on:
      - mariadb

  automats:
    build: ./UniteProd/
    networks:
      customnetwork:
        ipv4_address: 172.20.0.11
    depends_on:
      - collector
